use logicrs::{Lit, Var};
use std::ops::{Index, IndexMut};

use super::clause::CRef;

/// Gate type — corresponds to X-SAT `gate_type` enum (solver.h:36)
///
///   UNUSE → slot not yet assigned (excluded from Rust: we use Option<GateVar>)
///   INPUT → primary input from the circuit
///   AND   → AND gate with two fanin literals
///   XOR   → XOR gate (recovered from AIG structure)
///   LUT   → Look-Up Table gate (created during structural variable elimination)
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GateType {
    Input,
    And,
    Xor,
    Lut,
}

/// Circuit-aware variable — corresponds to X-SAT `Variable` struct (solver.h:46-61)
///
/// In X-SAT, the solver maintains circuit topology: each variable knows its gate type,
/// fanin (inputs to this gate), fanout (gates that consume this gate's output),
/// and XOR connectivity. This is what makes X-SAT "circuit-aware" vs a plain CNF solver.
///
/// Field mapping:
///   is_input    → Variable::is_input     — primary input of the circuit
///   is_output   → Variable::is_output    — primary output of the circuit
///   gate_type   → Variable::type         — AND/XOR/INPUT/LUT
///   fanin       → Variable::fanin_lits   — input literals to this gate
///   fanout      → Variable::fanout_vars  — downstream gate variables
///   clauses     → Variable::clauses      — CNF clauses generated by this gate
///   neighbors   → Variable::neighbors    — XOR-connected variables (for XVSIDS)
///   is_deleted  → Variable::is_delete    — eliminated during preprocessing
///   xor_edges   → Variable::xor_edges    — XOR edge count (XVSIDS coefficient)
///   lut_phase   → Variable::lut_phase    — positive probability from LUT simulation
pub struct GateVar {
    pub is_input: bool,
    pub is_output: bool,
    pub gate_type: GateType,
    pub fanin: Vec<Lit>,
    pub fanout: Vec<Var>,
    pub clauses: Vec<CRef>,
    pub neighbors: Vec<Var>,
    pub is_deleted: bool,
    pub xor_edges: u32,
    pub lut_phase: f64,
}

impl GateVar {
    pub fn new(gate_type: GateType) -> Self {
        Self {
            is_input: gate_type == GateType::Input,
            is_output: false,
            gate_type,
            fanin: Vec::new(),
            fanout: Vec::new(),
            clauses: Vec::new(),
            neighbors: Vec::new(),
            is_deleted: false,
            xor_edges: 0,
            lut_phase: 0.0,
        }
    }

    /// The output literal of this gate — always positive polarity.
    /// X-SAT: `Variable::out` stores `var << 1` which is the positive literal.
    /// In logicrs: `Var(v).lit()` gives the positive literal.
    #[inline]
    pub fn out_lit(&self, var: Var) -> Lit {
        var.lit()
    }
}

/// Reason type for a variable assignment.
/// Corresponds to X-SAT `type_assigned::reason` (solver.h:72-75)
///
/// X-SAT encodes the reason as `pair<int, int>` where `.second` is a type tag:
///   -2  → decision variable (no reason)          → Decision
///   -1  → direct implicate (circuit structure)    → Direct(lit_id)
///   -3  → output forced true at level 0           → Output
///   -4  → clause implicate (watched clause)       → Clause(cref)
#[derive(Clone, Copy, Debug)]
pub enum Reason {
    Decision,
    Direct(Lit),
    Output,
    Clause(CRef),
}

/// Assignment record — corresponds to X-SAT `type_assigned` (solver.h:72-75)
///
/// Each variable stores its decision level and the reason for its assignment.
/// X-SAT: `assigned[var].level` and `assigned[var].reason`
pub struct Assign {
    pub level: u32,
    pub reason: Reason,
}

impl Default for Assign {
    fn default() -> Self {
        Self {
            level: 0,
            reason: Reason::Decision,
        }
    }
}

/// Gate variable storage — replaces X-SAT's parallel arrays `var_mem[]` and `lit_mem[]`
///
/// X-SAT allocates:
///   `var_mem = new Variable[maxvar + 1]`  (solver.cpp:32)
///   `lit_mem = new Literal[maxlit + 1]`   (solver.cpp:33)
///   `assigned = new type_assigned[maxvar + 1]` (solver.cpp:51)
///   `value = new int[maxlit + 1]`         (solver.cpp:53)
///
/// Rust: we use a single struct-of-arrays via Vec, indexed by Var.
/// The `Literal` struct (fanout_AND_start/end, direct_start/end) is for
/// circuit-aware propagation (Phase 3) and is deferred to that phase.
pub struct GateVarMap<T> {
    data: Vec<T>,
}

impl<T: Default> GateVarMap<T> {
    pub fn new() -> Self {
        Self { data: Vec::new() }
    }

    pub fn with_capacity(cap: usize) -> Self {
        Self {
            data: Vec::with_capacity(cap),
        }
    }

    /// Ensure the map has space for `var`, filling gaps with default values.
    pub fn reserve(&mut self, var: Var) {
        let idx = *var as usize;
        if idx >= self.data.len() {
            self.data.resize_with(idx + 1, T::default);
        }
    }
}

impl<T> Default for GateVarMap<T>
where
    T: Default,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<T> Index<Var> for GateVarMap<T> {
    type Output = T;
    #[inline]
    fn index(&self, index: Var) -> &Self::Output {
        &self.data[*index as usize]
    }
}

impl<T> IndexMut<Var> for GateVarMap<T> {
    #[inline]
    fn index_mut(&mut self, index: Var) -> &mut Self::Output {
        &mut self.data[*index as usize]
    }
}

/// Three-valued assignment: true / false / unassigned.
/// Corresponds to X-SAT's `value[]` array (solver.cpp:53)
/// where `value[lit]` is 1 (true), -1 (false), or 0 (unassigned).
///
/// X-SAT indexes by literal: `value[lit]`. We provide both lit and var access.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TriVal {
    False,
    True,
    None,
}

impl TriVal {
    #[inline]
    pub fn is_true(self) -> bool {
        self == TriVal::True
    }

    #[inline]
    pub fn is_false(self) -> bool {
        self == TriVal::False
    }

    #[inline]
    pub fn is_none(self) -> bool {
        self == TriVal::None
    }
}

impl Default for TriVal {
    fn default() -> Self {
        TriVal::None
    }
}

/// Literal-indexed assignment storage.
/// X-SAT: `value = new int[maxlit + 1]` with `value[lit] = {0, 1, -1}`.
/// We store per-literal, indexed by the Lit's internal u32 encoding.
pub struct LitAssign {
    data: Vec<TriVal>,
}

impl LitAssign {
    pub fn new() -> Self {
        Self { data: Vec::new() }
    }

    pub fn reserve_lit(&mut self, lit: Lit) {
        let idx = u32::from(lit) as usize;
        if idx >= self.data.len() {
            self.data.resize(idx + 1, TriVal::None);
        }
    }

    pub fn reserve_var(&mut self, var: Var) {
        self.reserve_lit(var.lit());
        self.reserve_lit(!var.lit());
    }

    /// Get the truth value of a literal.
    /// X-SAT: `value[lit]` returns 1/-1/0.
    /// Returns True if the literal is satisfied, False if falsified, None if unassigned.
    #[inline]
    pub fn val(&self, lit: Lit) -> TriVal {
        let idx = u32::from(lit) as usize;
        if idx < self.data.len() {
            self.data[idx]
        } else {
            TriVal::None
        }
    }

    /// Assign a literal to true.
    /// X-SAT: `value[lit] = 1; value[notlit(lit)] = -1;` (solver.cpp:98)
    #[inline]
    pub fn assign(&mut self, lit: Lit) {
        let idx = u32::from(lit) as usize;
        if idx >= self.data.len() {
            self.data.resize(idx + 1, TriVal::None);
        }
        self.data[idx] = TriVal::True;
        self.data[u32::from(!lit) as usize] = TriVal::False;
    }

    /// Unassign a variable (used during backtracking).
    /// X-SAT: `value[var2lit(var)] = 0; value[var2lit(-var)] = 0;`
    #[inline]
    pub fn unassign(&mut self, var: Var) {
        let pos = u32::from(var.lit()) as usize;
        let neg = u32::from(!var.lit()) as usize;
        if pos < self.data.len() {
            self.data[pos] = TriVal::None;
        }
        if neg < self.data.len() {
            self.data[neg] = TriVal::None;
        }
    }
}

impl Default for LitAssign {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gate_var_new() {
        let gv = GateVar::new(GateType::Input);
        assert!(gv.is_input);
        assert!(!gv.is_output);
        assert_eq!(gv.gate_type, GateType::Input);
        assert!(gv.fanin.is_empty());
        assert!(gv.fanout.is_empty());
        assert!(gv.neighbors.is_empty());
        assert_eq!(gv.xor_edges, 0);
        assert!(!gv.is_deleted);
    }

    #[test]
    fn test_gate_var_and() {
        let mut gv = GateVar::new(GateType::And);
        gv.fanin.push(Var(1).lit());
        gv.fanin.push(!Var(2).lit());
        assert_eq!(gv.fanin.len(), 2);
        assert_eq!(gv.gate_type, GateType::And);
        assert!(!gv.is_input);
    }

    #[test]
    fn test_gate_var_xor_edges() {
        let mut gv = GateVar::new(GateType::Xor);
        gv.xor_edges = 3;
        gv.neighbors.push(Var(5));
        gv.neighbors.push(Var(7));
        assert_eq!(gv.xor_edges, 3);
        assert_eq!(gv.neighbors.len(), 2);
    }

    #[test]
    fn test_gate_var_lut() {
        let mut gv = GateVar::new(GateType::Lut);
        gv.lut_phase = 0.75;
        assert_eq!(gv.gate_type, GateType::Lut);
        assert!((gv.lut_phase - 0.75).abs() < 1e-10);
    }

    #[test]
    fn test_reason_variants() {
        let r1 = Reason::Decision;
        let r2 = Reason::Direct(Var(3).lit());
        let r3 = Reason::Output;
        let r4 = Reason::Clause(CRef::from(42));

        match r1 {
            Reason::Decision => {}
            _ => panic!("expected Decision"),
        }
        match r2 {
            Reason::Direct(lit) => assert_eq!(lit, Var(3).lit()),
            _ => panic!("expected Direct"),
        }
        match r3 {
            Reason::Output => {}
            _ => panic!("expected Output"),
        }
        match r4 {
            Reason::Clause(cr) => assert_eq!(cr, CRef::from(42)),
            _ => panic!("expected Clause"),
        }
    }

    #[test]
    fn test_assign_default() {
        let a = Assign::default();
        assert_eq!(a.level, 0);
        matches!(a.reason, Reason::Decision);
    }

    #[test]
    fn test_lit_assign() {
        let mut la = LitAssign::new();
        let v = Var(5);
        let pos = v.lit();
        let neg = !v.lit();

        la.reserve_var(v);
        assert!(la.val(pos).is_none());
        assert!(la.val(neg).is_none());

        la.assign(pos);
        assert!(la.val(pos).is_true());
        assert!(la.val(neg).is_false());

        la.unassign(v);
        assert!(la.val(pos).is_none());
        assert!(la.val(neg).is_none());
    }

    #[test]
    fn test_lit_assign_neg() {
        let mut la = LitAssign::new();
        let v = Var(3);
        la.assign(!v.lit());
        assert!(la.val(v.lit()).is_false());
        assert!(la.val(!v.lit()).is_true());
    }

    #[test]
    fn test_gate_var_map() {
        let mut map = GateVarMap::<Assign>::new();
        let v = Var(5);
        map.reserve(v);
        assert_eq!(map[v].level, 0);
        map[v].level = 3;
        assert_eq!(map[v].level, 3);
    }

    #[test]
    fn test_out_lit() {
        let gv = GateVar::new(GateType::And);
        let out = gv.out_lit(Var(10));
        assert_eq!(out, Var(10).lit());
        assert!(out.polarity());
    }
}
